In [1]:
from datasets import load_dataset
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display

/Users/cm/Library/Mobile Documents/com~apple~CloudDocs/文件/UCI Courses/275 NLP/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ds = load_dataset("datastax/linkedin_job_listings")
print("rows:", ds.num_rows)
print("cols:", len(ds.column_names))

rows: {'train': 123849}
cols: 1

In [3]:
df = ds["train"].to_pandas()[["job_id", "company_id", "title", "description"]]
df.head()

,job_id,company_id,title,description
0,921716,2774458.0,Marketing Coordinator,Job descriptionA leading real estate firm in N...
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ..."
2,10998357,64896719.0,Assitant Restaurant Manager,The National Exemplar is accepting application...
3,23221523,766262.0,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...

In [4]:
df.loc[:4, "description"].tolist()

['Job descriptionA leading real estate firm in New Jersey is seeking an administrative Marketing Coordinator with some experience in graphic design. You will be working closely with our fun, kind, ambitious members of the sales team and our dynamic executive team on a daily basis. This is an opportunity to be part of a fast-growing, highly respected real estate brokerage with a reputation for exceptional marketing and extraordinary culture of cooperation and inclusion.Who you are:You must be a well-organized, creative, proactive, positive, and most importantly, kind-hearted person. Please, be responsible, respectful, and cool-under-pressure. Please, be proficient in Adobe Creative Cloud (Indesign, Illustrator, Photoshop) and Microsoft Office Suite. Above all, have fantastic taste and be a good-hearted, fun-loving person who loves working with people and is eager to learn.Role:Our office is a fast-paced environment. You’ll work directly with a Marketing team and communicate daily with other core staff and our large team of agents. This description is a brief overview, but your skills and interests will be considered in what you work on and as the role evolves over time.Agent Assistance- Receive & Organize Marketing Requests from Agents- Track Tasks & Communicate with Marketing team & Agents on Status- Prepare print materials and signs for open houses- Submit Orders to Printers & Communicate & Track DeadlinesGraphic Design & Branding- Managing brand strategy and messaging through website, social media, videos, online advertising, print placement and events- Receive, organize, and prioritize marketing requests from agents- Fulfill agent design requests including postcards, signs, email marketing and property brochures using pre-existing templates and creating custom designs- Maintain brand assets and generic filesEvents & Community- Plan and execute events and promotions- Manage Contacts & Vendors for Event Planning & SponsorshipsOur company is committed to creating a diverse environment and is proud to be an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, gender, gender identity or expression, sexual orientation, national origin, genetics, disability, age, or veteran status.Job Type: Full-time\nPay: $18-20/hour\nExpected hours: 35 – 45 per week\nBenefits:Paid time offSchedule:8 hour shiftMonday to FridayExperience:Marketing: 1 year (Preferred)Graphic design: 2 years (Preferred)Work Location: In person\n',
 'At Aspen Therapy and Wellness , we are committed to serving clients with best practices to help them with change, improvements and better quality of life. We believe in providing a secure, supportive environment to grow as a clinician and learn how to foster longevity in the career which is part of our mission statement.\nThank you for taking the time to explore a career with us. We are excited to be a new group practice in the community. If you are looking for quality supervision as you work towards licensure and ability to serve populations while accepting a variety of insurance panels, we may be a good fit. Our supervisors are trained in EMDR and utilize a parts work perspective with a trauma lens.\nWe are actively looking to hire a therapist in the area who is passionate about working with adults and committed to growth and excellence in the field. We are located in Old Town Square, Fort Collins.\nWe value and are strengthened by diversity and desire a warm and welcoming place for all people. We believe in racial and ethnic equality, gender equity and social inclusion.\nPosition Requirement Possibilities:A graduate level psychological counseling-related degreeMasters of Social Work (MSW/LSW)Licensed Professional Counselor Candidate (LPCC)Clinical Social worker (LCSW)Professional Counselor (LPC)Marriage/Family Therapist (LMFT)Relating to this?Wanting to deliver high quality mental healthcareSeeking quality supervision and growth in a healthy environmentWhat we offer:Flexible work scheduleW2 Employment - commission basedBuilding to full time workJump of 5% in commission as well as monthly bonus/stipend once full timeWeekly supervision providedPaid weekly team meetings $30/hrTwo paid wellness hours/month $30/hrTelemedicine and in-person flexibilitySupportive work environment with direct access to two supervisorsAdministrative supportApproved professional development training providedFully automated EHR and technology supportStrong work/life balanceJob Duties:Conducting intake assessmentsDeveloping and implementing treatment plans for clients based on assessment and coordinating any additional services needed, revising as necessaryConducting individual sessions as appropriate for the treatment plan of the patientApplying psychotherapeutic techniques and interventions in the delivery of services to individuals for the purpose of treating emotional and behavioral disorders that have been diagnosed in assessmentParticipating in team meetings in order to staff new cases. Presenting appropriate patient information to the team. Recommending effective treatment interventions.Building and maintaining an active caseload with assigned clientsCompleting timely progress notes and treatment updates in the EHR. Maintaining all clinical documentation in accordance with regulatory and accrediting standardsProviding crisis intervention to patients in acute distress and referring as neededPerforming case management and discharge planning as neededExcellent communication and interpersonal skillsCompassionate and empathetic approach to patient carePlease send resume and cover letter to info@aspentherapyandwellness.com\nAbout Aspen Therapy and Wellness LLCAspen Therapy and Wellness is a mental health services provider focusing on work with adults in an outpatient setting, working with a variety of mental health issues both in-person in Old Town Fort Collins and throughout the state of Colorado via telehealth services.\nPlease note that this job description is not exhaustive and additional duties may be assigned as needed.',
 'The National Exemplar is accepting applications for an Assistant Restaurant Manager.\nWe offer highly competitive wages, healthcare, paid time off, complimentary dining privileges and bonus opportunities. \nWe are a serious, professional, long-standing neighborhood restaurant with over 41 years of service. If you are looking for a long-term fit with a best in class organization then you should apply now. \nPlease send a resumes to pardom@nationalexemplar.com. o',
 'Senior Associate Attorney - Elder Law / Trusts and Estates  Our legal team is committed to providing each client with quality counsel, innovative solutions, and personalized service. Founded in 2000, the firm offers the legal expertise of its 115+ attorneys, who have accumulated experience and problem-solving skills over decades of practice.\nWe are a prominent Lake Success Law Firm seeking an associate attorney for its growing Elder Law and Estate Planning practice. The successful candidate will be a self-motivated, detail-oriented team member with strong communication skills and a desire to grow their practice. Experience with Estate Planning, Administration, and Litigation and is preferred.\n Responsibilities will include:\nCounseling clients with regard to estate planning and asset protection;Formulating and overseeing execution of Medicaid and estate plans;Drafting wills, revocable and irrevocable trusts, powers of attorney, health care proxies, and living wills;Estate Administration;Trust Administration;Court Appearances for Estate and Proceedings;Supervising paralegals \nQualifications:Juris Doctor degree (J.D.) from an accredited law schoolLicensed to practice law in New York10-15 years of experienceExperience with various advance directives, trusts, and willsStrong analytical and problem-solving skillsAbility to build rapport with clientsExcellent written and verbal communication skills\n Competitive salary commensurate with experienceSalary: $140,000- $175,000Benefits: 401k, Medical, Dental, Life Insurance, PTO, and more\nThis position is based out of Lake Success, NY ',
 'Looking for HVAC service tech with experience in commerical and industrial equipment. Minimum 5 yrs. on the job with mechanical license. Winger is a full line union mechanical business with Piping, plumbing, sheet metal and service.']

In [5]:
clean_title = df["title"].str.lower().str.strip()
clean_title.head(10)
df["clean_title"] = clean_title
s = df["clean_title"].head(1000)
s.value_counts().loc[lambda x: x > 1].head(10)

clean_title
project manager                    6
account executive                  6
associate attorney                 6
administrative assistant           5
marketing manager                  4
construction project manager       4
staff accountant                   4
customer service representative    4
software engineer                  3
account manager                    3
Name: count, dtype: int64

In [6]:
df_has_company = df[df["company_id"].notna()].copy()
df_has_company_dedup = df_has_company.drop_duplicates(
    subset=["company_id", "clean_title"], keep="first"
)
print(
    len(df_has_company),
    "->",
    len(df_has_company_dedup),
    "removed= ",
    len(df_has_company) - len(df_has_company_dedup),
)
df_has_company.head()

122132 -> 95502 removed=  26630

,job_id,company_id,title,description,clean_title
0,921716,2774458.0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,marketing coordinator
2,10998357,64896719.0,Assitant Restaurant Manager,The National Exemplar is accepting application...,assitant restaurant manager
3,23221523,766262.0,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,senior elder law / trusts and estates associat...
5,91700727,1481176.0,Economic Development and Planning Intern,Job summary:The Economic Development & Plannin...,economic development and planning intern
6,103254301,81942316.0,Producer,Company DescriptionRaw Cereal is a creative de...,producer

In [7]:
df_no_company = df[df["company_id"].isna()].copy()

In [8]:
df_no_company = df_no_company.drop_duplicates(subset=["description"], keep="first")
df_no_company = df_no_company[df_no_company["description"].notna()]
df_no_company.head()

,job_id,company_id,title,description,clean_title
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",mental health therapist/counselor
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,service technician
7,112576855,NaN,Building Engineer,Summary: Due to the pending retirement of our ...,building engineer
12,56482768,NaN,Appalachian Highlands Women's Business Center,FULL JOB DESCRIPTION – PROGRAM DIRECTOR Appala...,appalachian highlands women's business center
13,56924323,NaN,Structural Engineer,Universal Structural Engineers is seeking a st...,structural engineer

In [9]:
threshold = 0.95

texts = df_no_company["description"]
X = TfidfVectorizer(stop_words="english", min_df=2).fit_transform(texts)

S = cosine_similarity(X)
ii, jj = np.where(np.triu(S, k=1) >= threshold)

to_drop = set(df_no_company.index[j] for j in jj)

sample = list(to_drop)[:5]
for idx in sample:
    print("-------------------------")
    print(df_no_company.loc[idx, "description"][:800])

-------------------------
Manufacturing Engineer- Medical Device manufacturing - contract opportunity- benefits offered
Provides engineering support to the Product Transfer team, which executes Manufacturing Transfers and critical supply continuity projects.Supports PPAP and associated activities with new or existing suppliers.Possesses very good communicational skills and actively develop relationships with key stakeholders.This is an individual contributor role that requires the use of judgement in applying professional expertise and is expected to work independently with minimal supervision.A relevant BS Degree in Engineering and 4+ years of experience in medical devices or other similar highly regulated industries is required.
-------------------------
OTTO Agencies, under the umbrella of LLOYD Agencies, are hiring for sales management professionals across the United States.

WE ARE ONLY HIRING CANDIDATES IN TX, FL, MI, KY, IN, IL, AND GA


Remote and On-Site Opportunities available!
USA TODAY TOP WORKPLACE AWARD WINNERVoted "Top Workplace" by the Chicago Tribune every year from 2013 to current!Recently named one of the Top 50 Happiest Companies in the Country by Forbes!

Through our in house training, incredible leadership, and amazing starting incomes, our company has been able develop leaders and top customer service and sales professionals. We provide financial services and products to over 20,000 different labor organizations, financial institutions, small businesses, transportation and logistics companies nationwide.


We are activ
-------------------------
We are on a mission to empower individuals, families, and businesses with modern-day financial education. We operate as a non-captive broker dealer, partnering with industry leaders to provide essential financial services. We're expanding, and our agency building model offers opportunities to create a passive income stream.Position Overview:As a Financial Professional, you'll work remotely, setting your own schedule. No experience is required as we provide full training and mentorship. If you're motivated, ambitious, and value freedom and flexibility in your work, this is your opportunity to excel in the high-income financial services industry.Key Responsibilities:Educate clients on financial strategies and assist in planning for their financial goals.Collaborate with a supportive team and
-------------------------
OTTO Agencies, under the umbrella of LLOYD Agencies, are hiring for sales management professionals across the United States.
Remote and On-Site Opportunities available!


USA TODAY TOP WORKPLACE AWARD WINNERVoted "Top Workplace" by the Chicago Tribune every year from 2013 to current! Recently named one of the Top 50 Happiest Companies in the Country by Forbes!

Through our in house training, incredible leadership, and amazing starting incomes, our company has been able develop leaders and top customer service and sales professionals. We provide financial services and products to over 20,000 different labor organizations, financial institutions, small businesses, transportation and logistics companies nationwide.


We are actively hiring for experienced and entry level candidates to join o
-------------------------
OTTO Agencies, under the umbrella of LLOYD Agencies, are hiring for sales management professionals across the United States.
WE ARE ONLY HIRING CANDIDATES IN TX, FL, IN, MI, GA, AND KY.

Remote and On-Site Opportunities available!

USA TODAY TOP WORKPLACE AWARD WINNERVoted "Top Workplace" by the Chicago Tribune every year from 2013 to current!Recently named one of the Top 50 Happiest Companies in the Country by Forbes!

Through our in house training, incredible leadership, and amazing starting incomes, our company has been able develop leaders and top customer service and sales professionals. We provide financial services and products to over 20,000 different labor organizations, financial institutions, small businesses, transportation and logistics companies nationwide.


We are actively

In [10]:
df_no_company_dedup = df_no_company.drop(index=list(to_drop))

print(
    len(df_no_company),
    "->",
    len(df_no_company_dedup),
    "removed=",
    len(df_no_company) - len(df_no_company_dedup),
)

1695 -> 1668 removed= 27

In [11]:
df_cleaned = pd.concat([df_has_company_dedup, df_no_company_dedup], ignore_index=True)
display(df_cleaned[df_cleaned["company_id"].isna()].head(2))
df_cleaned[df_cleaned["company_id"].notna()].head(2)

,job_id,company_id,title,description,clean_title
95502,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",mental health therapist/counselor
95503,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,service technician

,job_id,company_id,title,description,clean_title
0,921716,2774458.0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,marketing coordinator
1,10998357,64896719.0,Assitant Restaurant Manager,The National Exemplar is accepting application...,assitant restaurant manager

In [12]:
import sqlite3

db_path = "linkedin_jobs_cleaned.sqlite"
table_name = "job_listings_cleaned"
meta_table_name = "column_metadata"

column_info = {
    "column_name": ["job_id", "title", "company", "company_id","description"],
    "description": ["Identifier to job", "Title of the job", "The company who posts this job", "Company identifier","Job description"],
    "data_type": ["int", "str", "str", "float","str"]
}
df_meta = pd.DataFrame(column_info)

conn = sqlite3.connect(db_path)

df_cleaned.to_sql(table_name, conn, if_exists="replace", index=False)

df_meta.to_sql(meta_table_name, conn, if_exists="replace", index=False)

conn.close()